feat: Rerendering with Media-Queries #1
wonjin-dev/1coin pull request #38
Opened 2022-03-23 14:00 UTC by PsmD

프로젝트가 재밌어 보여서, 관심 있던 와중 이슈에 올라온 미디어 쿼리에 대하여 구현해보았습니다.

2022-03-23 15:20 UTC, wonjin-dev requested changes
린트는 기존 포맷에 맞춰주세요.

작성하신 코드 예시화면도 첨부해주시면 좋을것 같아요

2022-03-25 15:02 UTC, PsmD commented
![original](https://user-images.githubusercontent.com/92723332/160145923-bff41f57-3a28-4d1a-a2d4-dcb68710b345.png)


1024px 밑으로 줄이면 원래 레이아웃으로 돌아오는 것 까지는 됐는데


![grid](https://user-images.githubusercontent.com/92723332/160145768-401e121a-29e4-4c94-a6ea-11025d80559d.png)

전체 화면일 때 새로운 레이아웃을 구성하는 과정에서 grid가 이상작동하는 문제가 생겼습니다.

2022-03-26 07:57 UTC, PsmD commented
창 크기가 1024px 위일 때는 아래의 레이아웃

![12](https://user-images.githubusercontent.com/92723332/160230196-8ef8e1f7-c8e9-4a51-a106-fec8b57a0887.png)

창 크기가 1024px 이하일 때는 아래의 레이아웃이 되도록 구성했습니다.
![122](https://user-images.githubusercontent.com/92723332/160230201-61073542-b3e7-4928-8505-e2cc3b245949.png)

그리고 코인 이미지를 제공해주던 cryptoicon-api가 2022년 03월 22일 부로 api 제공을 종료하여 https://cryptocurrencyliveprices.com 으로 이미지 소스를 수정했습니다.

2022-03-26 08:30 UTC, wonjin-dev approved these changes
LGTM : )

2022-03-26 08:30 UTC, merged